// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// ANNOTATION_TOKEN(token id, token value for human reading, token literal, token priority)
#ifdef ANNOTATION_TOKEN
ANNOTATION_TOKEN(EXCEPT, "except", "except", 0)
ANNOTATION_TOKEN(INCLUDE, "include", "include", 0)
ANNOTATION_TOKEN(PRIMAL, "primal", "primal", 0)
ANNOTATION_TOKEN(STAGE, "stage", "stage", 0)
ANNOTATION_TOKEN(MODE, "mode", "mode", 0)
ANNOTATION_TOKEN(FORWARD, "forward", "forward", 0)
ANNOTATION_TOKEN(BACKWARD, "backward", "backward", 0)
ANNOTATION_TOKEN(DUAL, "dual", "dual", 0)
ANNOTATION_TOKEN(ILLEGAL, "illegal", "", 0)
#endif
