
// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

/**
 * @file
 *
 * This file declares after-typecheck Java interop stage:
 * - generation of wrapping constructor for java impl reference wrapper.
 */
#ifndef CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_IMPL_WRAPPING_CONSTRUCTOR
#define CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_IMPL_WRAPPING_CONSTRUCTOR

#include "Context.h"
#include "InteropLibBridge.h"
#include "cangjie/AST/Node.h"

namespace Cangjie::Interop::Java {
class JavaDesugarManager;
}

namespace Cangjie::Native::FFI::Java {
using namespace Interop::Java;

struct AfterTypeCheckContext;
class AfterTypeCheckStage;

/**
 * Generates API stubs for Java Impls.
 * Note: Corresponding API for passing impl objects from java to cangjie is available after this stage (wrap/unwrap).
 */
class GenerateJavaImplApiStub : public AfterTypeCheckStage {
public:
    explicit GenerateJavaImplApiStub(JavaDesugarManager& man) : man(man)
    {
    }
protected:
    void Process(AfterTypeCheckContext& ctx) override;
private:
    void Process(AST::ClassDecl& refWrapper, AfterTypeCheckContext& ctx) const;

    JavaDesugarManager& man;
};

/**
 * Generates API stubs for Java Impls.
 * Note: Corresponding API for passing impl objects from java to cangjie is available after this stage (wrap/unwrap).
 */
class GenerateJavaImplWrappingConstructorStub : public AfterTypeCheckStage {
public:
    explicit GenerateJavaImplWrappingConstructorStub(JavaDesugarManager& man);
protected:
    void Process(AfterTypeCheckContext& ctx) override;
private:
    void Process(AST::ClassDecl& refWrapper, AfterTypeCheckContext& ctx) const;

    /**
     * Inserts wrapping constructor generated by `CreateWrappingConstructor` into java impl reference wrapper.
     * @see `GenerateWrappingConstructor`.
     */
    AST::FuncDecl& InsertWrappingConstructor(AST::ClassDecl& refWrapper) const;

    /**
     * Generates wrapping constructor stub without body.
     * At later stages, initialization logics is generated.
     * Example:
     * ```cangjie
     * init($obj: Java_CFFI_JavaEntity, $regId: RegistryId)
     * ```
     */
    OwnedPtr<AST::FuncDecl> CreateWrappingConstructorStub(AST::ClassDecl& refWrapper) const;

    JavaDesugarManager& man;
    TypeManager& typeManager;
    InteropLibBridge& ilib;
};

} // namespace Cangjie::Native::FFI::Java

#endif // CANGJIE_SEMA_AFTER_TYPECHECK_NATIVE_FFI_JAVA_GENERATE_JAVA_IMPL_WRAPPING_CONSTRUCTOR
