// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

package vardecl

public var a: Int32 = 1
public var b: Int32 = 1 + 2
public var c: Float32 = 1.0 + 2.0
public var d = true
private let e: Int32 = 1
