// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

// The Cangjie API is in Beta. For details on its capabilities and limitations, please refer to the README file.

/**
 * @file
 *
 * This file lists no side effect std function for further optimize.
 *
 */

"bg5roundFd$$d",
"at6StringS2==F6String$$b",
"at7Extend!l<:8HashableX8hashCodeF$$l",
"at7Extend!d<:8HashableX8hashCodeF$$l",
"at6StringS7compareF6String$$8Ordering",
"at7Extend!8Ordering<:10Comparable<8Ordering>X7compareF8Ordering$$8Ordering"
